Enable chgres on Gaea and move run_sfcanl_chgres.sh from global-workflow to this package

diff --git a/util/gdas_init/config b/util/gdas_init/config
--- a/util/gdas_init/config
+++ b/util/gdas_init/config
@@ -23,9 +23,13 @@
 # RUN_CHGRES   - To run chgres, set to 'yes'.  To extract
 #                data only, set to 'no'.
 # yy/mm/dd/hh  - The year/month/day/hour of your desired
-#                experiment.  Currently, does not support
-#                pre-ENKF GFS data, prior to
-#                2012 May 21 00z.  Use two digits.
+#                experiment. Use a four digit year and
+#                two digits for mon/day/hour. NOTE: The 
+#                standard build of chgres_cube does NOT
+#                support experiments prior to June 12,
+#                2019. To coldstart an experiment
+#                prior to these dates, contact a repository
+#                manager for assistance.
 # LEVS         - Number of hybrid levels plus 1.  To
 #                run with 64 levels, set LEVS to 65.
 # CRES_HIRES   - Resolution of the hires component of
@@ -44,37 +48,50 @@
 #                or incomplete. So this option may not
 #                always work. Contact george.gayno@noaa.gov
 #                if you encounter problems.
-# FRAC_ORO     - To use the latest orographic data, 
-#                set to 'yes', otherwise, set to 'no'.
-#                Note that: the latest orographic data
-#                support both frac_grid and none frac_grid in the UFS 
 #
 #-----------------------------------------------------------
 
-EXTRACT_DIR=/lfs/h2/emc/stmp/$USER/gdas.init/input
+echo ${machine}
+case "${machine}" in
+  "hera")  
+    EXTRACT_DIR="/scratch2/GFDL/gfdlscr/proj-shared/GFS_ICS"
+    OUTDIR="/scratch1/NCEPDEV/stmp4/${USER}/gdas.init/output"
+    ;;  
+  "gaea") 
+    EXTRACT_DIR="/gpfs/f5/gfdl_w/proj-shared/${USER}/GFS_ICS"
+    OUTDIR="/gpfs/f5/gfdl_w/proj-shared/${USER}/gdas.init/output"
+    ;;
+  *)
+    echo "FATAL: Unknown target machine ${machine}, couldn't set EXTRACT_DIR"
+    exit 1
+    ;;
+esac
+
+echo $EXTRACT_DIR
+
 EXTRACT_DATA=no
 
 RUN_CHGRES=yes
 
 yy=2022
-mm=05
-dd=06
-hh=06
+mm=06
+dd=09
+hh=18
 
 use_v16retro=no
 
-LEVS=65
+LEVS=128
 
 CDUMP=gdas
 
-FRAC_ORO=yes
-
-CRES_HIRES=C192
-CRES_ENKF=C96
+#CRES_HIRES=C768
+#CRES_ENKF=C384
+CRES_HIRES=C384
+CRES_ENKF=C192
+#CRES_HIRES=C192
+#CRES_ENKF=C96
 
 UFS_DIR=$PWD/../..
-
-OUTDIR=/lfs/h2/emc/stmp/$USER/gdas.init/output
 
 #---------------------------------------------------------
 # Dont touch anything below here.
@@ -86,22 +103,36 @@ EXEC_DIR=$UFS_DIR/exec
 if [ "$use_v16retro" = "yes" ]; then
 
   gfs_ver=v16retro
+  LEVS=128
 
 else
 
   gfs_ver=v16
+  LEVS=128
 
 # No ENKF data prior to 2012/05/21/00z
   if [ $yy$mm$dd$hh -lt 2012052100 ]; then
     set +x
-    echo FATAL ERROR: SCRIPTS DO NOT SUPPORT OLD GFS DATA
+    echo "FATAL ERROR: SCRIPTS DO NOT SUPPORT OLD GFS DATA."
     exit 2
   elif [ $yy$mm$dd$hh -lt 2016051000 ]; then
-    gfs_ver=v12
+#   gfs_ver=v12
+    set +x
+    echo "FATAL ERROR: V12 DATA NOT SUPPORTED."
+    echo "CONTACT A REPOSITORY MANAGER FOR ASSISTANCE."
+    exit 2
   elif [ $yy$mm$dd$hh -lt 2017072000 ]; then
-    gfs_ver=v13
+#   gfs_ver=v13
+    set +x
+    echo "FATAL ERROR: V13 DATA NOT SUPPORTED."
+    echo "CONTACT A REPOSITORY MANAGER FOR ASSISTANCE."
+    exit 2
   elif [ $yy$mm$dd$hh -lt 2019061200 ]; then
-    gfs_ver=v14
+#   gfs_ver=v14
+    set +x
+    echo "FATAL ERROR: V14 DATA NOT SUPPORTED."
+    echo "CONTACT A REPOSITORY MANAGER FOR ASSISTANCE."
+    exit 2
   elif [ $yy$mm$dd$hh -lt 2021032100 ]; then
     gfs_ver=v15
 # The way the v16 switch over was done, there is no complete
@@ -110,11 +141,17 @@ else
 # tarballs were archived starting 2021032106.
   elif [ $yy$mm$dd$hh -lt 2021032106 ]; then
     set +x
-    echo FATAL ERROR: NO V15 OR V16 DATA FOR 2021032100
+    echo "FATAL ERROR: NO V15 OR V16 DATA FOR 2021032100."
     exit 1
+  fi
+
+  if [ "$gfs_ver" != "v16" ]; then
+     LEVS=65
   fi
 
 fi
 
-export EXTRACT_DIR yy mm dd hh UFS_DIR OUTDIR CRES_HIRES CRES_ENKF FRAC_ORO
-export LEVS gfs_ver EXEC_DIR GDAS_INIT_DIR
+OUTDIR=${OUTDIR}/${gfs_ver}
+
+export EXTRACT_DIR yy mm dd hh UFS_DIR OUTDIR CRES_HIRES CRES_ENKF
+export LEVS gfs_ver EXEC_DIR GDAS_INIT_DIR FIXshield
